before_install:
- git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
- git fetch origin master
- git checkout origin/master
- git reset --hard && git clean -fd
- git rm -rf -q .
install:
- echo -e "machine github.com\nlogin $GITHUB_NAME\npassword $GITHUB_TOKEN" >> ~/.netrc
- curl http://www.phpshop.ru/loads/files/PHPShop-Enterprise-Trial.tar.gz | tar xz
script:
- git add .
- git commit -q -m 'Upd'
- git push origin HEAD:master
